### ISSUE TITLE
QA Testing Bugs

### ISSUE THREAD

**Issue by nightblade9** [nightblade9/furusiya#70]
Found some bugs while doing ad-hoc QA testing.

- [x] #29 is back from the dead
- [x] Frozen enemies don't die in one hit
- [x] Full resting with enemies in sight says `you rest for 24 turns` even though you didn't rest.
- [x] Pressing `escape` when there are frozen enemies crashes. Stack dump:
```
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    main_menu()
  File "main.py", line 113, in main_menu
    play_game()
  File "main.py", line 70, in play_game
    Game.ui.run()
  File "C:\Users\me\Code\furusiya\furusiya\view\adapter\tdl_adapter.py", line 33, in run
    self.app.run()
  File "C:\Users\me\Code\furusiya\furusiya\view\adapter\extensible_app.py", line 45, in run
    self.run_once()
  File "C:\Users\me\Code\furusiya\furusiya\view\adapter\extensible_app.py", line 59, in run_once
    getattr(self, method)(event)
  File "C:\Users\me\Code\furusiya\furusiya\model\keys\key_callbacks.py", line 20, in exit_to_main_menu_callback
    Game.save_manager.save()
  File "C:\Users\me\Code\furusiya\furusiya\data\save_manager.py", line 17, in save
    pickle.dump(to_pickle, f, pickle.HIGHEST_PROTOCOL)
AttributeError: Can't pickle local object 'FrozenMonster.__init__.<locals>.new_take_damage_strategy'
```
Screenshot:
![screenshot](https://i.imgur.com/5f21yp0.png)

Minor usability bugs:
- [x] Horse skill points don't display when unmounted.
- [x] Trying to use the lance charge when not mounted says `not enough skill points`
- [x] When you use frost-bomb, like `lance charge`, you should see something like `hit everything in a 5x5 area around you!`

**Comment by NegativeScript** [comment]
*Fin*
